# Generated by Django 2.2.12 on 2022-02-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0003_auto_20220202_0916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='track',
            new_name='Intake',
        ),
    ]
