# Generated by Django 2.2.12 on 2022-02-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0006_auto_20220203_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='intake',
            new_name='intake_id',
        ),
        migrations.RenameField(
            model_name='trainee',
            old_name='track',
            new_name='track_id',
        ),
    ]
